#! /bin/sh
bspc rule -r "*" &
zsh &
~/.config/polybar/start.sh
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xsetroot -cursor_name left_ptr &
dwall -s lake &
bspc config focus_follows_pointer true &
# xrandr --output (Monitor Name) --primary --mode (Resolution) --rotate normal #--output (Monitor Name) --mode (Resolution) --rotate normal --right-of (Monitor Name) &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         2
bspc config window_gap          5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config bottom_padding 0
bspc config top_padding 55

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a lxappearance state=floating follow=on rectangle 200x200+50+50 sticky=off
bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1    5"
bspc config presel_feedback_color "$color    1"

xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
